---
App:
  mode: single-run
  cycle-time-in-millis: 1000
WateringLogic:
  soil-moisture: soil
  humidity: airhumidity
  temperature: airtemp
  pump-controller: pump
  seconds-to-water: 3
  seconds-to-not-water: 3
SoilMoistureMeasurement:
  name: soil
  sensor: soilmoisture1
  threshold: 50
HumidityMeasurement:
  name: airhumidity
  sensor: therm
  threshold: 20
TemperatureMeasurement:
  name: airtemp
  sensor: therm
  threshold: 30
Pump:
  name: pump
  motor: ctrl
PwmMotorController:
  name: ctrl
  output0: 20
  output1: 21
  pwm: 17
Si7021Sensor:
  name: therm
Arduino:
  address: 12
  name-prefix: analog
  shutdownEnabledPin: 16
GroveSoilMoistureSensor:
  name: soilmoisture1
  input-name: analog.2
  water-voltage: 2.4
  dry-voltage: 3.6

