---
SoilMoistureMeasurement:
  name: soil
  sensor: soilmoisture1
HumidityMeasurement:
  name: airhumidity
  sensor: therm
TemperatureMeasurement:
  name: airtemp
  sensor: therm
Pump:
  name: pump
  motor: ctrl
PwmMotorController:
  name: ctrl
  output0: 20
  output1: 21
  pwm: 18
Si7021Sensor:
  name: therm
ADS1015:
  name-prefix: analog
GroveSoilMoistureSensor:
  name: soilmoisture1
  input-name: analog.2
  water-voltage: 2.4
  dry-voltage: 3.6

